// <auto-generated />
using System;
using BookDoc2026.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookDoc2026.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BookDocDbContext))]
    [Migration("20260809134733_NumericKeyBaseline")]
    partial class NumericKeyBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.BookableResource", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int>("CapacityMode")
                        .HasColumnType("int")
                        .HasColumnName("capacity_mode");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<long?>("ExternalReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_reference_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<int>("OperationalStatus")
                        .HasColumnType("int")
                        .HasColumnName("operational_status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "BranchId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "BranchId", "CategoryId", "IsActive", "OperationalStatus");

                    b.ToTable("bookable_resource", "resource", t =>
                        {
                            t.HasCheckConstraint("ck_bookable_resource_capacity", "[capacity] BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("ck_bookable_resource_capacity_mode", "[capacity_mode] BETWEEN 1 AND 2");

                            t.HasCheckConstraint("ck_bookable_resource_exclusive_capacity", "[capacity_mode] <> 1 OR [capacity] = 1");

                            t.HasCheckConstraint("ck_bookable_resource_status", "[operational_status] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ClinicalService", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("default_duration_minutes");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status", "Name");

                    b.ToTable("service", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_service_duration", "[default_duration_minutes] BETWEEN 5 AND 1440");

                            t.HasCheckConstraint("ck_catalog_service_status", "[status] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ResourceCapability", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("CapacityRequired")
                        .HasColumnType("int")
                        .HasColumnName("capacity_required");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<int?>("DurationOverrideMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_override_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ResourceId", "ServiceId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ServiceId", "IsActive");

                    b.ToTable("resource_capability", "resource", t =>
                        {
                            t.HasCheckConstraint("ck_resource_capability_capacity", "[capacity_required] BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("ck_resource_capability_duration", "[duration_override_minutes] IS NULL OR [duration_override_minutes] BETWEEN 5 AND 1440");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ResourceCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_category_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "ParentCategoryId");

                    b.HasIndex("TenantId", "Kind", "IsActive");

                    b.ToTable("resource_category", "resource", t =>
                        {
                            t.HasCheckConstraint("ck_resource_category_kind", "[kind] BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ResourceStatusEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "ResourceId");

                    b.HasIndex("TenantId", "ResourceId", "CreatedUtc");

                    b.ToTable("resource_status_event", "resource", t =>
                        {
                            t.HasCheckConstraint("ck_resource_status_event_from", "[from_status] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_resource_status_event_to", "[to_status] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ServiceResourceRequirement", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit")
                        .HasColumnName("is_optional");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("role_code");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "ServiceId", "CategoryId", "RoleCode")
                        .IsUnique();

                    b.ToTable("service_resource_requirement", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_service_resource_requirement_quantity", "[quantity] BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("action");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_json");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("TenantId", "CreatedUtc");

                    b.ToTable("audit_event", "audit");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.Branch", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "OrganizationId");

                    b.ToTable("branch", "org");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.BranchConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<int>("CommunicationVerificationStatus")
                        .HasColumnType("int")
                        .HasColumnName("communication_verification_status");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("EmailSender")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email_sender");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("invoice_prefix");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("ReceiptPrefix")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("receipt_prefix");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("whats_app_number");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.HasIndex("TenantId", "BranchId")
                        .IsUnique();

                    b.HasIndex("TenantId", "InvoicePrefix")
                        .IsUnique();

                    b.HasIndex("TenantId", "ReceiptPrefix")
                        .IsUnique();

                    b.ToTable("branch_configuration", "org");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.BranchPermissionGrant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("BranchUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_user_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<long>("GrantedByActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("granted_by_actor_id");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("permission");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "BranchUserId", "Permission")
                        .IsUnique();

                    b.ToTable("branch_permission_grant", "identity");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.BranchUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("role_code");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "SubjectId")
                        .IsUnique();

                    b.ToTable("branch_user", "identity");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.Organization", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("organization", "org");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lease_until_utc");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<DateTimeOffset>("NextAttemptUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_attempt_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("LeaseUntilUtc", "Status");

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.ToTable("outbox_message", "worker");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenant", "platform");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.TenantApplication", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("FirstBranchCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("first_branch_code");

                    b.Property<string>("FirstBranchName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("first_branch_name");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<long?>("ReviewedByActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by_actor_id");

                    b.Property<DateTimeOffset?>("ReviewedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("reviewed_utc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionSource")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("submission_source");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Status");

                    b.ToTable("tenant_application", "platform");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Patients.Patient", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("blood_group");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("PatientNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("patient_number");

                    b.Property<long>("RegistrationBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("registration_branch_id");

                    b.Property<string>("RegistrationPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .HasColumnName("registration_payload_hash")
                        .IsFixedLength();

                    b.Property<Guid>("RegistrationRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_request_id");

                    b.Property<long>("StakeholderId")
                        .HasColumnType("bigint")
                        .HasColumnName("stakeholder_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PatientNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "RegistrationRequestId")
                        .IsUnique();

                    b.HasIndex("TenantId", "StakeholderId")
                        .IsUnique();

                    b.HasIndex("TenantId", "RegistrationBranchId", "CreatedUtc");

                    b.ToTable("patient", "patient", t =>
                        {
                            t.HasCheckConstraint("ck_patient_status", "[status] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.AvailabilityException", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<int?>("CapacityOverride")
                        .HasColumnType("int")
                        .HasColumnName("capacity_override");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("end_utc");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("start_utc");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "ResourceId", "StartUtc", "EndUtc");

                    b.ToTable("availability_exception", "scheduling", t =>
                        {
                            t.HasCheckConstraint("ck_availability_exception_interval", "[start_utc] < [end_utc]");

                            t.HasCheckConstraint("ck_availability_exception_kind", "[kind] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.AvailabilityRule", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("LocalEnd")
                        .HasColumnType("time")
                        .HasColumnName("local_end");

                    b.Property<TimeOnly>("LocalStart")
                        .HasColumnType("time")
                        .HasColumnName("local_start");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<int>("SlotIntervalMinutes")
                        .HasColumnType("int")
                        .HasColumnName("slot_interval_minutes");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ServiceId");

                    b.HasIndex("TenantId", "BranchId", "ResourceId", "DayOfWeek", "IsActive");

                    b.ToTable("availability_rule", "scheduling", t =>
                        {
                            t.HasCheckConstraint("ck_availability_rule_capacity", "[capacity] BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("ck_availability_rule_interval", "[local_start] < [local_end]");

                            t.HasCheckConstraint("ck_availability_rule_slot", "[slot_interval_minutes] BETWEEN 5 AND 1440");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.ResourceReservation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("end_utc");

                    b.Property<long>("HoldId")
                        .HasColumnType("bigint")
                        .HasColumnName("hold_id");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("start_utc");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "ResourceId");

                    b.HasIndex("TenantId", "HoldId", "ResourceId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ResourceId", "StartUtc", "EndUtc");

                    b.ToTable("resource_reservation", "scheduling", t =>
                        {
                            t.HasCheckConstraint("ck_resource_reservation_interval", "[start_utc] < [end_utc]");

                            t.HasCheckConstraint("ck_resource_reservation_quantity", "[quantity] BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.SchedulingHold", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("end_utc");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_utc");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .HasColumnName("payload_hash")
                        .IsFixedLength();

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("start_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PatientId");

                    b.HasIndex("TenantId", "RequestId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ServiceId");

                    b.HasIndex("TenantId", "BranchId", "Status", "ExpiresUtc");

                    b.ToTable("hold", "scheduling", t =>
                        {
                            t.HasCheckConstraint("ck_scheduling_hold_interval", "[start_utc] < [end_utc]");

                            t.HasCheckConstraint("ck_scheduling_hold_status", "[status] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.Stakeholder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Type", "Status", "DisplayName");

                    b.ToTable("stakeholder", "stakeholder", t =>
                        {
                            t.HasCheckConstraint("ck_stakeholder_status", "[status] BETWEEN 1 AND 2");

                            t.HasCheckConstraint("ck_stakeholder_type", "[type] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderAddress", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("address_type");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("line2");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("postal_code");

                    b.Property<long>("StakeholderId")
                        .HasColumnType("bigint")
                        .HasColumnName("stakeholder_id");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("state_code");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StakeholderId")
                        .IsUnique()
                        .HasFilter("[is_primary] = 1");

                    b.HasIndex("TenantId", "StakeholderId", "AddressType")
                        .IsUnique();

                    b.ToTable("address", "stakeholder", t =>
                        {
                            t.HasCheckConstraint("ck_stakeholder_address_india_postal_code", "[country_code] = 'IN' AND LEN([postal_code]) = 6 AND [postal_code] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderContactPoint", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("normalized_value");

                    b.Property<long>("StakeholderId")
                        .HasColumnType("bigint")
                        .HasColumnName("stakeholder_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedValue");

                    b.HasIndex("TenantId", "StakeholderId", "Type")
                        .IsUnique()
                        .HasFilter("[is_primary] = 1");

                    b.HasIndex("TenantId", "StakeholderId", "Type", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("contact_point", "stakeholder", t =>
                        {
                            t.HasCheckConstraint("ck_stakeholder_contact_type", "[type] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderCorporate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("legal_name");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("registration_number");

                    b.Property<long>("StakeholderId")
                        .HasColumnType("bigint")
                        .HasColumnName("stakeholder_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradeName")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("trade_name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RegistrationNumber");

                    b.HasIndex("TenantId", "StakeholderId")
                        .IsUnique();

                    b.ToTable("corporate", "stakeholder");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderDocumentReference", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<long>("DocumentTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_type_id");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reference_number");

                    b.Property<long>("StakeholderId")
                        .HasColumnType("bigint")
                        .HasColumnName("stakeholder_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "FileId")
                        .IsUnique();

                    b.HasIndex("TenantId", "StakeholderId", "DocumentTypeId", "FileId")
                        .IsUnique();

                    b.ToTable("document_reference", "stakeholder");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderIdentifier", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("normalized_value");

                    b.Property<long>("StakeholderId")
                        .HasColumnType("bigint")
                        .HasColumnName("stakeholder_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StakeholderId", "IsActive");

                    b.HasIndex("TenantId", "Type", "Issuer", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("identifier", "stakeholder");
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderPerson", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AdministrativeSex")
                        .HasColumnType("int")
                        .HasColumnName("administrative_sex");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_utc");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("given_name");

                    b.Property<string>("Honorific")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("honorific");

                    b.Property<bool>("IsDateOfBirthEstimated")
                        .HasColumnType("bit")
                        .HasColumnName("is_date_of_birth_estimated");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_utc");

                    b.Property<string>("NormalizedSearchName")
                        .IsRequired()
                        .HasMaxLength(302)
                        .HasColumnType("nvarchar(302)")
                        .HasColumnName("normalized_search_name");

                    b.Property<long>("StakeholderId")
                        .HasColumnType("bigint")
                        .HasColumnName("stakeholder_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StakeholderId")
                        .IsUnique();

                    b.HasIndex("TenantId", "NormalizedSearchName", "DateOfBirth");

                    b.ToTable("person", "stakeholder", t =>
                        {
                            t.HasCheckConstraint("ck_stakeholder_person_sex", "[administrative_sex] BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.BookableResource", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Catalog.ResourceCategory", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ResourceCapability", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Catalog.BookableResource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ResourceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Catalog.ClinicalService", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ResourceCategory", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Catalog.ResourceCategory", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ParentCategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ResourceStatusEvent", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Catalog.BookableResource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId", "ResourceId")
                        .HasPrincipalKey("TenantId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Catalog.ServiceResourceRequirement", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Catalog.ResourceCategory", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Catalog.ClinicalService", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.Branch", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.BranchConfiguration", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Branch", null)
                        .WithOne()
                        .HasForeignKey("BookDoc2026.Domain.Foundation.BranchConfiguration", "TenantId", "BranchId")
                        .HasPrincipalKey("BookDoc2026.Domain.Foundation.Branch", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.BranchPermissionGrant", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.BranchUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId", "BranchUserId")
                        .HasPrincipalKey("TenantId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.BranchUser", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Foundation.Organization", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Patients.Patient", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RegistrationBranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Stakeholders.Stakeholder", null)
                        .WithOne()
                        .HasForeignKey("BookDoc2026.Domain.Patients.Patient", "TenantId", "StakeholderId")
                        .HasPrincipalKey("BookDoc2026.Domain.Stakeholders.Stakeholder", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.AvailabilityException", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Catalog.BookableResource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId", "ResourceId")
                        .HasPrincipalKey("TenantId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.AvailabilityRule", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Catalog.ClinicalService", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookDoc2026.Domain.Catalog.BookableResource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId", "ResourceId")
                        .HasPrincipalKey("TenantId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.ResourceReservation", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Scheduling.SchedulingHold", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "HoldId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Catalog.BookableResource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId", "ResourceId")
                        .HasPrincipalKey("TenantId", "BranchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Scheduling.SchedulingHold", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Foundation.Branch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PatientId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookDoc2026.Domain.Catalog.ClinicalService", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderAddress", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Stakeholders.Stakeholder", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "StakeholderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderContactPoint", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Stakeholders.Stakeholder", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "StakeholderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderCorporate", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Stakeholders.Stakeholder", null)
                        .WithOne()
                        .HasForeignKey("BookDoc2026.Domain.Stakeholders.StakeholderCorporate", "TenantId", "StakeholderId")
                        .HasPrincipalKey("BookDoc2026.Domain.Stakeholders.Stakeholder", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderDocumentReference", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Stakeholders.Stakeholder", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "StakeholderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderIdentifier", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Stakeholders.Stakeholder", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "StakeholderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookDoc2026.Domain.Stakeholders.StakeholderPerson", b =>
                {
                    b.HasOne("BookDoc2026.Domain.Stakeholders.Stakeholder", null)
                        .WithOne()
                        .HasForeignKey("BookDoc2026.Domain.Stakeholders.StakeholderPerson", "TenantId", "StakeholderId")
                        .HasPrincipalKey("BookDoc2026.Domain.Stakeholders.Stakeholder", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
